### ISSUE TITLE
International Day Event

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/reno#1]
Hello guys, @colinloretz  signed you up for the international day but it seems you havn't come around to setup an event site yet! See: nodeschool/international-day#22

**Comment by iancrowther** [comment]
is this event still happening?

**Comment by colinloretz** [comment]
@martinheidegger thanks, didn't get an email notification for this issue. Set up an eventbrite for Reno.

https://www.eventbrite.com/e/nodeschool-reno-may-2015-tickets-16932123437

@iancrowther are you in the Reno area or plan to be on May 23rd?

**Comment by iancrowther** [comment]
@colinloretz unfortunately not :-)

I'm just trying to finalise the Enrollment data
